"""
AGI Orchestrator LLM Extension

Adds LLM Decision Router integration to AGI Orchestrator.
This allows the AGI cycle to use reasoning models for dynamic decision-making.
"""

import logging
from typing import Dict, TYPE_CHECKING
from datetime import datetime

if TYPE_CHECKING:
    from src.agentic.agi_orchestrator import PhaseResult

logger = logging.getLogger(__name__)


async def run_phase_9_planning_with_llm(
    orchestrator,
    creative: Dict,
    meta: Dict,
    detection: Dict
) -> 'PhaseResult':
    """
    Phase 9: Multi-Step Planning with LLM Decision Router
    
    Instead of hardcoded plans, use LLM reasoning to generate
    dynamic action options based on current context.
    
    Args:
        orchestrator: AGI Orchestrator instance
        creative: Output from creative generation phase
        meta: Output from metacognition phase
        detection: Output from world state detection phase
    
    Returns:
        PhaseResult with LLM-generated plan
    """
    from src.agentic.agi_orchestrator import PhaseResult, Phase
    
    start = datetime.now()
    
    try:
        # Check if LLM Decision Router is available
        if not hasattr(orchestrator.core, 'agi_kernel'):
            logger.warning("AGI Kernel not available, falling back to standard planning")
            return orchestrator._run_phase_9_planning(creative, meta)
        
        llm_router = getattr(orchestrator.core.agi_kernel, 'llm_decision_router', None)
        
        if not llm_router:
            logger.warning("LLM Decision Router not available, falling back to standard planning")
            return orchestrator._run_phase_9_planning(creative, meta)
        
        # Use LLM Decision Router to generate action options
        logger.info("🧠 Using LLM Decision Router for planning...")
        
        action = await llm_router.decide_next_action()
        
        if not action:
            logger.info("   No action generated by LLM, falling back to standard planning")
            return orchestrator._run_phase_9_planning(creative, meta)
        
        # Convert LLM decision to plan format
        plan_steps = [
            {
                'step': 1,
                'action': 'llm_decision',
                'details': {
                    'action_type': action.get('action_type'),
                    'description': action.get('description'),
                    'goal_alignment': action.get('goal_alignment'),
                    'expected_outcome': action.get('expected_outcome'),
                    'timing': action.get('timing'),
                    'symod_score': action.get('symod_score'),
                    'decision_id': action.get('decision_id')
                }
            }
        ]
        
        output = {
            'plan_steps': plan_steps,
            'estimated_duration': 5,  # 5 min estimate
            'llm_generated': True,
            'decision_id': action.get('decision_id'),
            'symod_score': action.get('symod_score', 0),
            'ready_to_execute': True,
            'action': action  # Include full action for execution
        }
        
        logger.info(f"✅ LLM plan generated: {action.get('description', 'Unknown')[:60]}...")
        logger.info(f"   SyMod Score: {action.get('symod_score', 0):.2f}/100")
        
        return PhaseResult(
            phase=Phase.MULTI_STEP_PLANNING,
            success=True,
            output=output,
            confidence=action.get('symod_score', 70) / 100,  # Convert to 0-1
            duration_seconds=(datetime.now() - start).total_seconds(),
            triggered_phases=[Phase.EXECUTION]
        )
    
    except Exception as e:
        logger.error(f"LLM planning failed: {e}")
        logger.info("Falling back to standard planning")
        return orchestrator._run_phase_9_planning(creative, meta)
