"""
Autonomous Goal Formation System

This is where the agent becomes self-directed. Instead of only responding
to user commands, it:

1. Observes patterns in data (content performance, user behavior, on-chain activity)
2. Identifies opportunities or problems
3. Generates goals to capitalize on opportunities or fix problems
4. Prioritizes goals based on potential impact
5. Executes goals autonomously

This transforms AlleyBot from a command executor to a self-directed agent.
"""

import json
from typing import Dict, List, Any, Optional
from datetime import datetime, timedelta
from dataclasses import dataclass, asdict
from pathlib import Path
from enum import Enum


class GoalOrigin(Enum):
    """Where did this goal come from?"""
    USER_COMMAND = "user"      # User explicitly asked
    PERFORMANCE_GAP = "performance"  # Content underperforming
    OPPORTUNITY = "opportunity" # Detected opportunity (trending topic, etc.)
    RELATIONSHIP = "relationship" # User relationship maintenance
    ONCHAIN = "onchain"         # On-chain opportunity (price movement, etc.)
    REFLECTION = "reflection"   # Self-reflection identified need
    SYSTEM = "system"          # System maintenance


@dataclass
class AutonomousGoal:
    """
    A goal generated by the agent itself
    
    Unlike user-set goals, these have:
    - detected_opportunity: What the agent noticed
    - expected_outcome: What the agent thinks will happen
    - success_criteria: How to know if it worked
    """
    id: str
    description: str
    origin: GoalOrigin
    
    # What triggered this goal
    detected_opportunity: str
    evidence: Dict[str, Any]  # Data that led to this conclusion
    
    # Execution
    action_plan: List[str]  # Steps to take
    expected_outcome: str
    success_criteria: List[str]
    
    # Priority (0-10, higher = more important)
    priority_score: float = 5.0
    urgency: float = 5.0  # Time sensitivity
    impact: float = 5.0   # Potential benefit
    
    # Execution state
    current_step: int = 0
    
    # Status
    status: str = 'proposed'  # proposed, approved, active, completed, failed
    created_at: datetime = None
    activated_at: datetime = None
    completed_at: datetime = None
    
    # Results
    actual_outcome: str = None
    outcome_rating: float = 0.0  # -1 to 1
    
    def __post_init__(self):
        if self.created_at is None:
            self.created_at = datetime.now()
    
    def to_dict(self) -> Dict:
        return {
            'id': self.id,
            'description': self.description,
            'origin': self.origin.value,
            'detected_opportunity': self.detected_opportunity,
            'evidence': self.evidence,
            'action_plan': self.action_plan,
            'current_step': self.current_step,
            'expected_outcome': self.expected_outcome,
            'success_criteria': self.success_criteria,
            'priority_score': self.priority_score,
            'urgency': self.urgency,
            'impact': self.impact,
            'status': self.status,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'activated_at': self.activated_at.isoformat() if self.activated_at else None,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
            'actual_outcome': self.actual_outcome,
            'outcome_rating': self.outcome_rating
        }


class OpportunityDetector:
    """
    Analyzes data to find opportunities for the agent to act
    """
    
    def __init__(self, unified_memory=None, phase12_learning=None):
        self.memory = unified_memory
        self.phase12 = phase12_learning
    
    def detect_content_opportunities(self) -> List[Dict]:
        """
        Find content opportunities based on performance data
        
        Returns opportunities like:
        - "Topic X is trending but we haven't posted about it"
        - "Our posts about Y get 3x engagement, should post more"
        """
        opportunities = []
        
        if not self.phase12:
            return opportunities
        
        # 1. Check for high-performing topics we haven't covered recently
        top_topics = self.phase12.get_top_topics(limit=5, days=7)
        for topic_data in top_topics:
            topic = topic_data['topic']
            avg_engagement = topic_data.get('avg_engagement', 0)
            
            # If engagement is high, suggest more content
            if avg_engagement > 50:  # Threshold
                opportunities.append({
                    'type': 'content_gap',
                    'description': f"High engagement on '{topic}' ({avg_engagement:.1f} avg)",
                    'suggested_action': f"Create post about {topic}",
                    'expected_impact': avg_engagement * 1.2,
                    'urgency': 7
                })
        
        # 2. Check for rising topics (increasing engagement)
        trends = self.phase12.get_topic_trends(weeks=2)
        for week_key, week_data in trends.items():
            for item in week_data:
                topic = item.get('topic')
                engagement = item.get('avg_engagement', 0)
                if engagement > 30 and week_key == 'week_1':  # Recent week
                    opportunities.append({
                        'type': 'rising_topic',
                        'description': f"'{topic}' is trending up",
                        'suggested_action': f"Engage with {topic} content",
                        'expected_impact': engagement,
                        'urgency': 8
                    })
        
        return opportunities
    
    def detect_relationship_opportunities(self) -> List[Dict]:
        """
        Find opportunities to strengthen user relationships
        """
        opportunities = []
        
        if not self.phase12:
            return opportunities
        
        # Get active users we haven't interacted with recently
        active_users = self.phase12.get_active_community_members(days=7)
        
        for user in active_users:
            interaction_count = user.get('interaction_count', 0)
            last_interaction = user.get('last_interaction', '')
            
            # High-value users who need attention
            if interaction_count > 5:
                # Check if it's been a while
                try:
                    last_dt = datetime.fromisoformat(last_interaction.replace('Z', '+00:00'))
                    days_since = (datetime.now() - last_dt).days
                    
                    if days_since > 3:
                        opportunities.append({
                            'type': 'relationship_maintenance',
                            'description': f"User {user.get('username')} hasn't been engaged in {days_since} days",
                            'suggested_action': f"Reply to their content or send appreciation",
                            'expected_impact': interaction_count * 2,  # Value of relationship
                            'urgency': 6,
                            'target_user': user.get('user_id')
                        })
                except:
                    pass
        
        return opportunities
    
    def detect_onchain_opportunities(self, onchain_plugin=None) -> List[Dict]:
        """
        Find on-chain opportunities
        """
        opportunities = []
        
        if not onchain_plugin or not hasattr(onchain_plugin, 'web3_provider'):
            return opportunities
        
        # Check for significant balance changes
        if hasattr(onchain_plugin, 'token_snapshots') and onchain_plugin.token_snapshots:
            changes = onchain_plugin.check_balance_changes()
            if changes:
                for symbol, change_data in changes.items():
                    if change_data['change'] > 0:
                        opportunities.append({
                            'type': 'onchain_received',
                            'description': f"Received {change_data['change']:.4f} {symbol}",
                            'suggested_action': "Thank sender, acknowledge support",
                            'expected_impact': 10,
                            'urgency': 9
                        })
        
        return opportunities


class GoalGenerator:
    """
    Converts opportunities into autonomous goals using AGI reasoning
    """
    
    def __init__(self, unified_memory=None, unified_reasoner=None, phase12_learning=None):
        self.unified_memory = unified_memory
        self.unified_reasoner = unified_reasoner
        self.phase12 = phase12_learning
    
    def detect_content_opportunities(self) -> List[Dict]:
        """
        Find content opportunities based on performance data
        """
        opportunities = []
        
        if not self.phase12:
            return opportunities
        
        # 1. Check for high-performing topics we haven't covered recently
        top_topics = self.phase12.get_top_topics(limit=5, days=7)
        for topic_data in top_topics:
            topic = topic_data['topic']
            avg_engagement = topic_data.get('avg_engagement', 0)
            
            # If engagement is high, suggest more content
            if avg_engagement > 50:  # Threshold
                opportunities.append({
                    'type': 'content_gap',
                    'description': f"High engagement on '{topic}' ({avg_engagement:.1f} avg)",
                    'suggested_action': f"Create post about {topic}",
                    'expected_impact': avg_engagement * 1.2,
                    'urgency': 7
                })
        
        # 2. Check for rising topics (increasing engagement)
        trends = self.phase12.get_topic_trends(weeks=2)
        for week_key, week_data in trends.items():
            for item in week_data:
                topic = item.get('topic')
                engagement = item.get('avg_engagement', 0)
                if engagement > 30 and week_key == 'week_1':  # Recent week
                    opportunities.append({
                        'type': 'rising_topic',
                        'description': f"'{topic}' is trending up",
                        'suggested_action': f"Engage with {topic} content",
                        'expected_impact': engagement,
                        'urgency': 8
                    })
        
        return opportunities
    
    def generate_goal_from_opportunity(self, opportunity: Dict[str, Any]) -> Optional[AutonomousGoal]:
        """Generate a goal from an opportunity using AGI reasoning"""
        try:
            # Use UnifiedReasoner for strategic goal planning if available
            if self.unified_reasoner:
                from src.agentic.unified_reasoner import ReasoningContext, ReasoningType
                
                reasoning_ctx = ReasoningContext(
                    problem=f"Create actionable goal from opportunity: {opportunity.get('title', 'Unknown')}",
                    domain=opportunity.get('type', 'general'),
                    reasoning_type=ReasoningType.STRATEGIC,
                    related_domains=['social', 'trading', 'content'],
                    constraints={
                        'opportunity_type': opportunity.get('type'),
                        'confidence': opportunity.get('confidence', 0.5),
                        'urgency': opportunity.get('urgency', 'medium'),
                    },
                    goal='Create concrete action plan with predicted outcomes',
                    confidence_threshold=0.6
                )
                
                reasoning_result = self.unified_reasoner.reason(reasoning_ctx)
                
                if reasoning_result and reasoning_result.confidence >= 0.6:
                    # Extract action plan from reasoning
                    action_plan = self._extract_action_plan_from_reasoning(
                        reasoning_result, 
                        opportunity
                    )
                    if action_plan:
                        opportunity['reasoned_action_plan'] = action_plan
                        opportunity['reasoning_confidence'] = reasoning_result.confidence
                        logger.info(f"🧠 Reasoner generated action plan with confidence {reasoning_result.confidence:.2f}")
            
            # Continue with goal creation
            goal_id = f"goal_auto_{datetime.now().timestamp()}"
            
            # Build action plan based on type
            action_plan = [opportunity['suggested_action']]
            if opportunity['type'] == 'content_gap':
                action_plan.extend([
                    "Generate content using AI",
                    "Post to appropriate platform",
                    "Track engagement"
                ])
            elif opportunity['type'] == 'relationship_maintenance':
                action_plan.extend([
                    "Find user's recent content",
                    "Generate thoughtful reply",
                    "Record interaction"
                ])
            
            return AutonomousGoal(
                id=goal_id,
                description=opportunity['description'],
                origin=GoalOrigin.OPPORTUNITY,
                detected_opportunity=opportunity['description'],
                evidence={'opportunity_data': opportunity},
                action_plan=action_plan,
                expected_outcome=f"{opportunity['expected_impact']:.1f} engagement points",
                success_criteria=[
                    f"Achieve {opportunity['expected_impact'] * 0.8:.1f} impact",
                    "Complete all action steps"
                ],
                priority_score=min(10, opportunity.get('expected_impact', 5) / 10),
                urgency=opportunity.get('urgency', 5),
                impact=opportunity.get('expected_impact', 5)
            )
        
        except Exception as e:
            logger.error(f"Error generating goal from opportunity: {e}")
            return None
    
    def generate_goals(self, onchain_plugin=None) -> List[AutonomousGoal]:
        """
        Generate goals from all opportunity sources
        """
        goals = []
        
        # 1. Content opportunities
        content_ops = self.detect_content_opportunities()
        for opp in content_ops:
            goal = self.generate_goal_from_opportunity(opp)
            if goal:
                goals.append(goal)
        
        # 2. Relationship opportunities
        rel_ops = OpportunityDetector().detect_relationship_opportunities()
        for opp in rel_ops:
            goal = self.generate_goal_from_opportunity(opp)
            if goal:
                goals.append(goal)
        
        # 3. On-chain opportunities
        if onchain_plugin:
            chain_ops = OpportunityDetector().detect_onchain_opportunities(onchain_plugin)
            for opp in chain_ops:
                goal = self.generate_goal_from_opportunity(opp)
                if goal:
                    goals.append(goal)
        
        # Sort by priority score
        goals.sort(key=lambda g: g.priority_score, reverse=True)
        return goals
    
    def _extract_action_plan_from_reasoning(self, reasoning_result, opportunity):
        """Extract concrete action plan from UnifiedReasoner output."""
        if not reasoning_result or not reasoning_result.decision:
            return None
        
        decision_text = str(reasoning_result.decision)
        
        # Parse action steps from reasoning output
        action_plan = []
        
        # Look for numbered steps or bullet points
        lines = decision_text.split('\n')
        for line in lines:
            line = line.strip()
            if line and (line[0].isdigit() or line.startswith('-') or line.startswith('•')):
                # Clean up the line
                clean_line = line.lstrip('0123456789.-•) ').strip()
                if clean_line and len(clean_line) > 10:
                    action_plan.append(clean_line)
        
        # Fallback: use opportunity type to generate plan
        if not action_plan:
            if opportunity['type'] == 'content_gap':
                action_plan = [
                    "Generate content using AI",
                    "Post to appropriate platform",
                    "Track engagement"
                ]
            elif opportunity['type'] == 'relationship_maintenance':
                action_plan = [
                    "Find user's recent content",
                    "Generate thoughtful reply",
                    "Record interaction"
                ]
        
        return AutonomousGoal(
            id=goal_id,
            description=opp['description'],
            origin=origin,
            detected_opportunity=opp['description'],
            evidence={'opportunity_data': opp},
            action_plan=action_plan,
            expected_outcome=f"{opp['expected_impact']:.1f} engagement points",
            success_criteria=[
                f"Achieve {opp['expected_impact'] * 0.8:.1f} impact",
                "Complete all action steps"
            ],
            priority_score=min(10, opp.get('expected_impact', 5) / 10),
            urgency=opp.get('urgency', 5),
            impact=opp.get('expected_impact', 5)
        )


class AutonomousGoalManager:
    """
    Autonomous goal generation facade.
    
    This class handles **goal generation** (opportunity detection → goal proposal)
    but delegates all **goal storage** to GoalManager v2 (SQLite-backed).
    
    This ensures a single authoritative goal store while preserving the
    autonomous scanning/generation logic.
    """
    
    def __init__(self, storage_path: str = 'data/autonomous_goals.json'):
        self.generator: Optional[GoalGenerator] = None
        self._goal_manager_v2 = None  # Lazily resolved
        # Legacy path kept only for one-time migration
        self._legacy_path = Path(storage_path)
    
    @property
    def goal_manager_v2(self):
        """Lazily get GoalManager v2 (SQLite) as the single store."""
        if self._goal_manager_v2 is None:
            try:
                from src.agentic.goal_manager import get_goal_manager
                self._goal_manager_v2 = get_goal_manager()
            except Exception as e:
                print(f"⚠️ Could not resolve GoalManager v2: {e}")
        return self._goal_manager_v2
    
    def initialize_generator(self, unified_memory, phase12_learning, onchain_plugin=None):
        """Initialize goal generation with dependencies"""
        detector = OpportunityDetector(unified_memory, phase12_learning)
        self.generator = GoalGenerator(detector)
    
    def _autonomous_goal_to_v2(self, ag: AutonomousGoal):
        """Convert an AutonomousGoal to a GoalManager v2 Goal."""
        from src.agentic.goal_manager import Goal, GoalPriority, GoalStatus as V2Status
        
        # Map priority score to GoalPriority enum
        if ag.priority_score >= 9:
            priority = GoalPriority.CRITICAL
        elif ag.priority_score >= 7:
            priority = GoalPriority.HIGH
        elif ag.priority_score >= 5:
            priority = GoalPriority.MEDIUM
        elif ag.priority_score >= 3:
            priority = GoalPriority.LOW
        else:
            priority = GoalPriority.BACKLOG
        
        return Goal(
            id=ag.id,
            title=ag.description[:120],
            description=ag.description,
            category='optimization',
            priority=priority,
            impact_score=ag.impact,
            effort_estimate='hours',
            confidence=min(ag.priority_score / 10.0, 1.0),
            trigger_type=ag.origin.value if ag.origin else 'opportunity',
            trigger_data=ag.evidence if isinstance(ag.evidence, dict) else {'evidence': ag.evidence},
            evidence=ag.success_criteria if isinstance(ag.success_criteria, list) else [],
            status=V2Status.PROPOSED,
        )
    
    def scan_and_generate(self, onchain_plugin=None) -> List[AutonomousGoal]:
        """
        Scan for opportunities and generate new goals.
        
        Generated goals are stored in GoalManager v2 (SQLite).
        """
        if not self.generator:
            print("⚠️ Goal generator not initialized")
            return []
        
        new_goals = self.generator.generate_goals(onchain_plugin)
        
        # Store in GoalManager v2 (single authoritative store)
        gm = self.goal_manager_v2
        filtered_goals = []
        for goal in new_goals:
            if gm:
                v2_goal = self._autonomous_goal_to_v2(goal)
                if gm.add_goal(v2_goal):
                    filtered_goals.append(goal)
            else:
                filtered_goals.append(goal)
        
        if filtered_goals:
            print(f"🎯 Generated {len(filtered_goals)} autonomous goals → GoalManager v2 (SQLite)")
            for g in filtered_goals:
                print(f"   - {g.description} (priority: {g.priority_score:.1f})")
        
        return filtered_goals
    
    def approve_goal(self, goal_id: str) -> bool:
        """Approve a goal — delegates to GoalManager v2."""
        gm = self.goal_manager_v2
        if gm:
            return gm.approve_goal(goal_id)
        return False
    
    def get_next_action(self) -> Optional[Dict]:
        """Get next action from active goals — delegates to GoalManager v2."""
        gm = self.goal_manager_v2
        if not gm:
            return None
        
        from src.agentic.goal_manager import GoalStatus as V2Status
        active_goals = gm.get_goals(status=V2Status.ACTIVE, limit=5)
        if not active_goals:
            return None
        
        for goal in sorted(active_goals, key=lambda g: g.impact_score, reverse=True):
            action = gm.get_next_action_for_goal(goal)
            if action:
                return action
        return None
    
    def complete_action(self, goal_id: str, success: bool, outcome: str = None):
        """Mark action complete — delegates to GoalManager v2."""
        gm = self.goal_manager_v2
        if not gm:
            return False
        
        if success:
            return gm.complete_goal(goal_id, outcome=outcome or "Completed via autonomous action")
        else:
            # Use safe-goal failure tracking (includes backoff and cooling)
            if hasattr(gm, 'record_safe_goal_failure'):
                return gm.record_safe_goal_failure(
                    goal_id, note=outcome or "Failed via autonomous action"
                )
            return False
    
    def get_active_goals(self) -> List[Dict]:
        """Get active goals from GoalManager v2."""
        gm = self.goal_manager_v2
        if not gm:
            return []
        from src.agentic.goal_manager import GoalStatus as V2Status
        goals = gm.get_goals(status=V2Status.ACTIVE, limit=20)
        return [{'id': g.id, 'description': g.description, 'title': g.title,
                 'priority_score': g.impact_score, 'status': 'active',
                 'category': g.category} for g in goals]
    
    def get_proposed_goals(self) -> List[Dict]:
        """Get proposed goals from GoalManager v2."""
        gm = self.goal_manager_v2
        if not gm:
            return []
        from src.agentic.goal_manager import GoalStatus as V2Status
        goals = gm.get_goals(status=V2Status.PROPOSED, limit=20)
        return [{'id': g.id, 'description': g.description, 'title': g.title,
                 'priority_score': g.impact_score, 'status': 'proposed',
                 'category': g.category} for g in goals]


# Factory function
def create_autonomous_goal_manager(
    unified_memory=None,
    phase12_learning=None,
    onchain_plugin=None
) -> AutonomousGoalManager:
    """Create and initialize autonomous goal manager"""
    manager = AutonomousGoalManager()
    if unified_memory and phase12_learning:
        manager.initialize_generator(unified_memory, phase12_learning, onchain_plugin)
    return manager
