"""
Autonomous Goal Formation System

This is where the agent becomes self-directed. Instead of only responding
to user commands, it:

1. Observes patterns in data (content performance, user behavior, on-chain activity)
2. Identifies opportunities or problems
3. Generates goals to capitalize on opportunities or fix problems
4. Prioritizes goals based on potential impact
5. Executes goals autonomously

This transforms AlleyBot from a command executor to a self-directed agent.
"""

import json
from typing import Dict, List, Any, Optional
from datetime import datetime, timedelta
from dataclasses import dataclass, asdict
from pathlib import Path
from enum import Enum


class GoalOrigin(Enum):
    """Where did this goal come from?"""
    USER_COMMAND = "user"      # User explicitly asked
    PERFORMANCE_GAP = "performance"  # Content underperforming
    OPPORTUNITY = "opportunity" # Detected opportunity (trending topic, etc.)
    RELATIONSHIP = "relationship" # User relationship maintenance
    ONCHAIN = "onchain"         # On-chain opportunity (price movement, etc.)
    REFLECTION = "reflection"   # Self-reflection identified need
    SYSTEM = "system"          # System maintenance


@dataclass
class AutonomousGoal:
    """
    A goal generated by the agent itself
    
    Unlike user-set goals, these have:
    - detected_opportunity: What the agent noticed
    - expected_outcome: What the agent thinks will happen
    - success_criteria: How to know if it worked
    """
    id: str
    description: str
    origin: GoalOrigin
    
    # What triggered this goal
    detected_opportunity: str
    evidence: Dict[str, Any]  # Data that led to this conclusion
    
    # Execution
    action_plan: List[str]  # Steps to take
    expected_outcome: str
    success_criteria: List[str]
    
    # Priority (0-10, higher = more important)
    priority_score: float = 5.0
    urgency: float = 5.0  # Time sensitivity
    impact: float = 5.0   # Potential benefit
    
    # Execution state
    current_step: int = 0
    
    # Status
    status: str = 'proposed'  # proposed, approved, active, completed, failed
    created_at: datetime = None
    activated_at: datetime = None
    completed_at: datetime = None
    
    # Results
    actual_outcome: str = None
    outcome_rating: float = 0.0  # -1 to 1
    
    def __post_init__(self):
        if self.created_at is None:
            self.created_at = datetime.now()
    
    def to_dict(self) -> Dict:
        return {
            'id': self.id,
            'description': self.description,
            'origin': self.origin.value,
            'detected_opportunity': self.detected_opportunity,
            'evidence': self.evidence,
            'action_plan': self.action_plan,
            'current_step': self.current_step,
            'expected_outcome': self.expected_outcome,
            'success_criteria': self.success_criteria,
            'priority_score': self.priority_score,
            'urgency': self.urgency,
            'impact': self.impact,
            'status': self.status,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'activated_at': self.activated_at.isoformat() if self.activated_at else None,
            'completed_at': self.completed_at.isoformat() if self.completed_at else None,
            'actual_outcome': self.actual_outcome,
            'outcome_rating': self.outcome_rating
        }


class OpportunityDetector:
    """
    Analyzes data to find opportunities for the agent to act
    """
    
    def __init__(self, unified_memory=None, phase12_learning=None):
        self.memory = unified_memory
        self.phase12 = phase12_learning
    
    def detect_content_opportunities(self) -> List[Dict]:
        """
        Find content opportunities based on performance data
        
        Returns opportunities like:
        - "Topic X is trending but we haven't posted about it"
        - "Our posts about Y get 3x engagement, should post more"
        """
        opportunities = []
        
        if not self.phase12:
            return opportunities
        
        # 1. Check for high-performing topics we haven't covered recently
        top_topics = self.phase12.get_top_topics(limit=5, days=7)
        for topic_data in top_topics:
            topic = topic_data['topic']
            avg_engagement = topic_data.get('avg_engagement', 0)
            
            # If engagement is high, suggest more content
            if avg_engagement > 50:  # Threshold
                opportunities.append({
                    'type': 'content_gap',
                    'description': f"High engagement on '{topic}' ({avg_engagement:.1f} avg)",
                    'suggested_action': f"Create post about {topic}",
                    'expected_impact': avg_engagement * 1.2,
                    'urgency': 7
                })
        
        # 2. Check for rising topics (increasing engagement)
        trends = self.phase12.get_topic_trends(weeks=2)
        for week_key, week_data in trends.items():
            for item in week_data:
                topic = item.get('topic')
                engagement = item.get('avg_engagement', 0)
                if engagement > 30 and week_key == 'week_1':  # Recent week
                    opportunities.append({
                        'type': 'rising_topic',
                        'description': f"'{topic}' is trending up",
                        'suggested_action': f"Engage with {topic} content",
                        'expected_impact': engagement,
                        'urgency': 8
                    })
        
        return opportunities
    
    def detect_relationship_opportunities(self) -> List[Dict]:
        """
        Find opportunities to strengthen user relationships
        """
        opportunities = []
        
        if not self.phase12:
            return opportunities
        
        # Get active users we haven't interacted with recently
        active_users = self.phase12.get_active_community_members(days=7)
        
        for user in active_users:
            interaction_count = user.get('interaction_count', 0)
            last_interaction = user.get('last_interaction', '')
            
            # High-value users who need attention
            if interaction_count > 5:
                # Check if it's been a while
                try:
                    last_dt = datetime.fromisoformat(last_interaction.replace('Z', '+00:00'))
                    days_since = (datetime.now() - last_dt).days
                    
                    if days_since > 3:
                        opportunities.append({
                            'type': 'relationship_maintenance',
                            'description': f"User {user.get('username')} hasn't been engaged in {days_since} days",
                            'suggested_action': f"Reply to their content or send appreciation",
                            'expected_impact': interaction_count * 2,  # Value of relationship
                            'urgency': 6,
                            'target_user': user.get('user_id')
                        })
                except:
                    pass
        
        return opportunities
    
    def detect_onchain_opportunities(self, onchain_plugin=None) -> List[Dict]:
        """
        Find on-chain opportunities
        """
        opportunities = []
        
        if not onchain_plugin or not hasattr(onchain_plugin, 'web3_provider'):
            return opportunities
        
        # Check for significant balance changes
        if hasattr(onchain_plugin, 'token_snapshots') and onchain_plugin.token_snapshots:
            changes = onchain_plugin.check_balance_changes()
            if changes:
                for symbol, change_data in changes.items():
                    if change_data['change'] > 0:
                        opportunities.append({
                            'type': 'onchain_received',
                            'description': f"Received {change_data['change']:.4f} {symbol}",
                            'suggested_action': "Thank sender, acknowledge support",
                            'expected_impact': 10,
                            'urgency': 9
                        })
        
        return opportunities


class GoalGenerator:
    """
    Converts opportunities into autonomous goals using AGI reasoning
    """
    
    def __init__(self, unified_memory=None, unified_reasoner=None, phase12_learning=None):
        self.unified_memory = unified_memory
        self.unified_reasoner = unified_reasoner
        self.phase12 = phase12_learning
    
    def detect_content_opportunities(self) -> List[Dict]:
        """
        Find content opportunities based on performance data
        """
        opportunities = []
        
        if not self.phase12:
            return opportunities
        
        # 1. Check for high-performing topics we haven't covered recently
        top_topics = self.phase12.get_top_topics(limit=5, days=7)
        for topic_data in top_topics:
            topic = topic_data['topic']
            avg_engagement = topic_data.get('avg_engagement', 0)
            
            # If engagement is high, suggest more content
            if avg_engagement > 50:  # Threshold
                opportunities.append({
                    'type': 'content_gap',
                    'description': f"High engagement on '{topic}' ({avg_engagement:.1f} avg)",
                    'suggested_action': f"Create post about {topic}",
                    'expected_impact': avg_engagement * 1.2,
                    'urgency': 7
                })
        
        # 2. Check for rising topics (increasing engagement)
        trends = self.phase12.get_topic_trends(weeks=2)
        for week_key, week_data in trends.items():
            for item in week_data:
                topic = item.get('topic')
                engagement = item.get('avg_engagement', 0)
                if engagement > 30 and week_key == 'week_1':  # Recent week
                    opportunities.append({
                        'type': 'rising_topic',
                        'description': f"'{topic}' is trending up",
                        'suggested_action': f"Engage with {topic} content",
                        'expected_impact': engagement,
                        'urgency': 8
                    })
        
        return opportunities
    
    def generate_goal_from_opportunity(self, opportunity: Dict[str, Any]) -> Optional[AutonomousGoal]:
        """Generate a goal from an opportunity using AGI reasoning"""
        try:
            # Use UnifiedReasoner for strategic goal planning if available
            if self.unified_reasoner:
                from src.agentic.unified_reasoner import ReasoningContext, ReasoningType
                
                reasoning_ctx = ReasoningContext(
                    problem=f"Create actionable goal from opportunity: {opportunity.get('title', 'Unknown')}",
                    domain=opportunity.get('type', 'general'),
                    reasoning_type=ReasoningType.STRATEGIC,
                    related_domains=['social', 'trading', 'content'],
                    constraints={
                        'opportunity_type': opportunity.get('type'),
                        'confidence': opportunity.get('confidence', 0.5),
                        'urgency': opportunity.get('urgency', 'medium'),
                    },
                    goal='Create concrete action plan with predicted outcomes',
                    confidence_threshold=0.6
                )
                
                reasoning_result = self.unified_reasoner.reason(reasoning_ctx)
                
                if reasoning_result and reasoning_result.confidence >= 0.6:
                    # Extract action plan from reasoning
                    action_plan = self._extract_action_plan_from_reasoning(
                        reasoning_result, 
                        opportunity
                    )
                    if action_plan:
                        opportunity['reasoned_action_plan'] = action_plan
                        opportunity['reasoning_confidence'] = reasoning_result.confidence
                        logger.info(f"🧠 Reasoner generated action plan with confidence {reasoning_result.confidence:.2f}")
            
            # Continue with goal creation
            goal_id = f"goal_auto_{datetime.now().timestamp()}"
            
            # Build action plan based on type
            action_plan = [opportunity['suggested_action']]
            if opportunity['type'] == 'content_gap':
                action_plan.extend([
                    "Generate content using AI",
                    "Post to appropriate platform",
                    "Track engagement"
                ])
            elif opportunity['type'] == 'relationship_maintenance':
                action_plan.extend([
                    "Find user's recent content",
                    "Generate thoughtful reply",
                    "Record interaction"
                ])
            
            return AutonomousGoal(
                id=goal_id,
                description=opportunity['description'],
                origin=GoalOrigin.OPPORTUNITY,
                detected_opportunity=opportunity['description'],
                evidence={'opportunity_data': opportunity},
                action_plan=action_plan,
                expected_outcome=f"{opportunity['expected_impact']:.1f} engagement points",
                success_criteria=[
                    f"Achieve {opportunity['expected_impact'] * 0.8:.1f} impact",
                    "Complete all action steps"
                ],
                priority_score=min(10, opportunity.get('expected_impact', 5) / 10),
                urgency=opportunity.get('urgency', 5),
                impact=opportunity.get('expected_impact', 5)
            )
        
        except Exception as e:
            logger.error(f"Error generating goal from opportunity: {e}")
            return None
    
    def generate_goals(self, onchain_plugin=None) -> List[AutonomousGoal]:
        """
        Generate goals from all opportunity sources
        """
        goals = []
        
        # 1. Content opportunities
        content_ops = self.detect_content_opportunities()
        for opp in content_ops:
            goal = self.generate_goal_from_opportunity(opp)
            if goal:
                goals.append(goal)
        
        # 2. Relationship opportunities
        rel_ops = OpportunityDetector().detect_relationship_opportunities()
        for opp in rel_ops:
            goal = self.generate_goal_from_opportunity(opp)
            if goal:
                goals.append(goal)
        
        # 3. On-chain opportunities
        if onchain_plugin:
            chain_ops = OpportunityDetector().detect_onchain_opportunities(onchain_plugin)
            for opp in chain_ops:
                goal = self.generate_goal_from_opportunity(opp)
                if goal:
                    goals.append(goal)
        
        # Sort by priority score
        goals.sort(key=lambda g: g.priority_score, reverse=True)
        return goals
    
    def _extract_action_plan_from_reasoning(self, reasoning_result, opportunity):
        """Extract concrete action plan from UnifiedReasoner output."""
        if not reasoning_result or not reasoning_result.decision:
            return None
        
        decision_text = str(reasoning_result.decision)
        
        # Parse action steps from reasoning output
        action_plan = []
        
        # Look for numbered steps or bullet points
        lines = decision_text.split('\n')
        for line in lines:
            line = line.strip()
            if line and (line[0].isdigit() or line.startswith('-') or line.startswith('•')):
                # Clean up the line
                clean_line = line.lstrip('0123456789.-•) ').strip()
                if clean_line and len(clean_line) > 10:
                    action_plan.append(clean_line)
        
        # Fallback: use opportunity type to generate plan
        if not action_plan:
            if opportunity['type'] == 'content_gap':
                action_plan = [
                    "Generate content using AI",
                    "Post to appropriate platform",
                    "Track engagement"
                ]
            elif opportunity['type'] == 'relationship_maintenance':
                action_plan = [
                    "Find user's recent content",
                    "Generate thoughtful reply",
                    "Record interaction"
                ]
        
        return AutonomousGoal(
            id=goal_id,
            description=opp['description'],
            origin=origin,
            detected_opportunity=opp['description'],
            evidence={'opportunity_data': opp},
            action_plan=action_plan,
            expected_outcome=f"{opp['expected_impact']:.1f} engagement points",
            success_criteria=[
                f"Achieve {opp['expected_impact'] * 0.8:.1f} impact",
                "Complete all action steps"
            ],
            priority_score=min(10, opp.get('expected_impact', 5) / 10),
            urgency=opp.get('urgency', 5),
            impact=opp.get('expected_impact', 5)
        )


class AutonomousGoalManager:
    """
    Manages the lifecycle of autonomously generated goals
    """
    
    def __init__(self, storage_path: str = 'data/autonomous_goals.json'):
        self.storage_path = Path(storage_path)
        self.storage_path.parent.mkdir(parents=True, exist_ok=True)
        self.goals: List[AutonomousGoal] = []
        self.generator: Optional[GoalGenerator] = None
        self._load()
    
    def initialize_generator(self, unified_memory, phase12_learning, onchain_plugin=None):
        """Initialize goal generation with dependencies"""
        detector = OpportunityDetector(unified_memory, phase12_learning)
        self.generator = GoalGenerator(detector)
    
    def scan_and_generate(self, onchain_plugin=None) -> List[AutonomousGoal]:
        """
        Scan for opportunities and generate new goals
        
        This is the main entry point - call this periodically to have
        the agent generate its own objectives.
        """
        if not self.generator:
            print("⚠️ Goal generator not initialized")
            return []
        
        new_goals = self.generator.generate_goals(onchain_plugin)
        
        # Filter out duplicates (similar goals already pending)
        filtered_goals = []
        for goal in new_goals:
            if not self._is_duplicate(goal):
                goal.status = 'proposed'
                self.goals.append(goal)
                filtered_goals.append(goal)
        
        if filtered_goals:
            print(f"🎯 Generated {len(filtered_goals)} new autonomous goals")
            for g in filtered_goals:
                print(f"   - {g.description} (priority: {g.priority_score:.1f})")
        
        self._save()
        return filtered_goals
    
    def approve_goal(self, goal_id: str) -> bool:
        """
        Approve a proposed goal for execution
        
        In full autonomy mode, this could be automatic for high-confidence goals.
        For now, user approval or auto-approve high-priority goals.
        """
        for goal in self.goals:
            if goal.id == goal_id:
                if goal.priority_score >= 8.0:
                    # Auto-approve high-priority goals
                    goal.status = 'active'
                    goal.activated_at = datetime.now()
                    print(f"✅ Auto-approved high-priority goal: {goal.description}")
                else:
                    goal.status = 'approved'
                    print(f"⏳ Goal approved (waiting execution): {goal.description}")
                self._save()
                return True
        return False
    
    def get_next_action(self) -> Optional[Dict]:
        """
        Get the next action to execute from active goals
        
        Returns action with context, or None if no active goals
        """
        active_goals = [g for g in self.goals if g.status == 'active']
        if not active_goals:
            return None
        
        # Sort by priority and progress
        active_goals.sort(key=lambda g: (g.priority_score, -g.current_step), reverse=True)
        
        top_goal = active_goals[0]

        def build_action(plugin: str, action_type: str, params: Dict[str, Any]) -> Dict[str, Any]:
            return {
                'plugin': plugin,
                'action_type': action_type,
                'params': params,
                'context': {
                    'goal_driven': True,
                    'goal_id': top_goal.id,
                    'goal_description': top_goal.description,
                    'impact': 'high',
                    'source': 'autonomous_goal_manager',
                    'evidence': top_goal.evidence,
                },
                'step': top_goal.current_step + 1,
                'total_steps': len(top_goal.action_plan),
                'origin': top_goal.origin.value,
                'goal_id': top_goal.id,  # Top-level for easy access
                'goal_description': top_goal.description,  # Top-level for DecisionSystem
                'description': f"Goal: {top_goal.description}",  # For logging
            }
        
        if top_goal.current_step < len(top_goal.action_plan):
            action = top_goal.action_plan[top_goal.current_step]
            
            # Parse plugin:action_type format
            if ':' in str(action):
                parts = str(action).split(':', 1)
                if len(parts) == 2:
                    plugin = parts[0].strip()
                    action_type = parts[1].strip()
                    return build_action(plugin, action_type, {})
            
            # Fallback: keyword matching for generic action descriptions
            action_text = str(action).lower()
            if 'engage' in action_text or 'reply' in action_text or 'comment' in action_text:
                return build_action('moltx', 'engage', {'count': 3})
            if 'post' in action_text or 'write' in action_text or 'publish' in action_text:
                return build_action('moltx', 'post', {'topic': top_goal.description})
            if 'analy' in action_text or 'performance' in action_text or 'metric' in action_text:
                return build_action('analytics', 'analyze', {'time_window': '7d'})
            if 'check' in action_text and 'notification' in action_text:
                # Extract platform from action text
                for platform in ['moltx', 'clawbr', 'moltchan', 'telegram']:
                    if platform in action_text:
                        return build_action(platform, 'check_notifications', {})
                return build_action('moltx', 'check_notifications', {})

            return {
                'goal_id': top_goal.id,
                'goal_description': top_goal.description,
                'action': action,
                'step': top_goal.current_step + 1,
                'total_steps': len(top_goal.action_plan),
                'origin': top_goal.origin.value
            }
        
        return None
    
    def complete_action(self, goal_id: str, success: bool, outcome: str = None):
        """Mark current action as complete and advance"""
        for goal in self.goals:
            if goal.id == goal_id:
                if success:
                    goal.current_step += 1
                    
                    # Check if goal complete
                    if goal.current_step >= len(goal.action_plan):
                        goal.status = 'completed'
                        goal.completed_at = datetime.now()
                        goal.actual_outcome = outcome
                        goal.outcome_rating = 0.5  # Default positive
                        print(f"✅ Completed goal: {goal.description}")
                else:
                    goal.status = 'failed'
                    goal.actual_outcome = outcome
                    goal.outcome_rating = -0.5
                    print(f"❌ Failed goal: {goal.description}")
                
                self._save()
                return True
        return False
    
    def get_active_goals(self) -> List[Dict]:
        """Get all active goals as dicts"""
        return [g.to_dict() for g in self.goals if g.status == 'active']
    
    def get_proposed_goals(self) -> List[Dict]:
        """Get goals waiting for approval"""
        return [g.to_dict() for g in self.goals if g.status == 'proposed']
    
    def _is_duplicate(self, new_goal: AutonomousGoal) -> bool:
        """Check if similar goal already exists"""
        for existing in self.goals:
            if existing.status in ['completed', 'failed']:
                continue
            # Similar description or same opportunity type
            if (existing.detected_opportunity == new_goal.detected_opportunity or
                existing.description == new_goal.description):
                return True
        return False
    
    def _save(self):
        """Persist goals"""
        try:
            data = [g.to_dict() for g in self.goals]
            with open(self.storage_path, 'w') as f:
                json.dump(data, f, indent=2)
        except Exception as e:
            print(f"⚠️ Failed to save goals: {e}")
    
    def _load(self):
        """Load goals"""
        try:
            if self.storage_path.exists():
                with open(self.storage_path, 'r') as f:
                    data = json.load(f)
                self.goals = []
                # Handle both old format (list) and new format (dict with 'goals' key)
                goals_data = data.get('goals', []) if isinstance(data, dict) else data
                for gdata in goals_data:
                    # Reconstruct goal
                    goal = AutonomousGoal(
                        id=gdata['id'],
                        description=gdata['description'],
                        origin=GoalOrigin(gdata['origin']),
                        detected_opportunity=gdata['detected_opportunity'],
                        evidence=gdata.get('evidence', {}),
                        action_plan=gdata.get('action_plan', []),
                        current_step=gdata.get('current_step', 0),
                        expected_outcome=gdata.get('expected_outcome', ''),
                        success_criteria=gdata.get('success_criteria', []),
                        priority_score=gdata.get('priority_score', 5.0),
                        urgency=gdata.get('urgency', 5.0),
                        impact=gdata.get('impact', 5.0),
                        status=gdata.get('status', 'proposed'),
                        actual_outcome=gdata.get('actual_outcome'),
                        outcome_rating=gdata.get('outcome_rating', 0.0)
                    )
                    goal.created_at = datetime.fromisoformat(gdata['created_at']) if gdata.get('created_at') else datetime.now()
                    self.goals.append(goal)
                print(f"✅ Loaded {len(self.goals)} autonomous goals ({len([g for g in self.goals if g.status == 'active'])} active)")
        except Exception as e:
            print(f"⚠️ Failed to load goals: {e}")


# Factory function
def create_autonomous_goal_manager(
    unified_memory=None,
    phase12_learning=None,
    onchain_plugin=None
) -> AutonomousGoalManager:
    """Create and initialize autonomous goal manager"""
    manager = AutonomousGoalManager()
    if unified_memory and phase12_learning:
        manager.initialize_generator(unified_memory, phase12_learning, onchain_plugin)
    return manager
