"""
LLM Decision Router

Revolutionary decision-making system that uses LLM reasoning models to generate
dynamic action options, then validates them mathematically with SyMod.

NO HARDCODED ACTIONS - Everything is generated by reasoning models based on context.

Flow:
1. Gather context from decision silos (goals, opportunities, world state)
2. Ask LLM reasoning model to generate 3-5 action options
3. Score each option with SyMod (mathematical validation)
4. Select best option
5. Store decision + outcome to memory
6. Learn and improve over time

Supported Reasoning Models:
- Grok (XAI) - For planning and strategic reasoning
- DeepSeek Reasoner - For deep analytical reasoning
"""

import json
import logging
from typing import Dict, List, Optional
from datetime import datetime
from dataclasses import dataclass, field

logger = logging.getLogger(__name__)


@dataclass
class DecisionOption:
    """A single action option generated by LLM"""
    action: str
    goal_alignment: str
    expected_outcome: str
    timing: str
    resources_needed: str
    risk_level: str
    
    # Added by SyMod scoring
    symod_score: float = 0.0
    symod_breakdown: Dict = field(default_factory=dict)
    symod_reasoning: str = ""
    symod_confidence: float = 0.0
    
    def to_dict(self) -> Dict:
        return {
            'action': self.action,
            'goal_alignment': self.goal_alignment,
            'expected_outcome': self.expected_outcome,
            'timing': self.timing,
            'resources_needed': self.resources_needed,
            'risk_level': self.risk_level,
            'symod_score': self.symod_score,
            'symod_breakdown': self.symod_breakdown,
            'symod_reasoning': self.symod_reasoning,
            'symod_confidence': self.symod_confidence
        }


@dataclass
class DecisionRecord:
    """Record of a decision for learning"""
    decision_id: str
    timestamp: str
    context: Dict
    options_considered: List[Dict]
    selected_option: Dict
    symod_reasoning: str
    
    # Filled in after execution
    outcome: Optional[Dict] = None
    success: Optional[bool] = None
    learning: Optional[str] = None
    
    def to_dict(self) -> Dict:
        return {
            'decision_id': self.decision_id,
            'timestamp': self.timestamp,
            'context': self.context,
            'options_considered': self.options_considered,
            'selected_option': self.selected_option,
            'symod_reasoning': self.symod_reasoning,
            'outcome': self.outcome,
            'success': self.success,
            'learning': self.learning
        }


class DecisionMemory:
    """
    Stores decisions and outcomes for learning.
    
    Enables:
    - Learning from past decisions
    - Understanding what works
    - Improving future decisions
    """
    
    def __init__(self, storage_path: str = 'data/decision_memory.json'):
        self.storage_path = storage_path
        self.decisions = {}
        self._load()
    
    def _load(self):
        """Load decisions from storage"""
        try:
            import os
            if os.path.exists(self.storage_path):
                with open(self.storage_path, 'r') as f:
                    data = json.load(f)
                    self.decisions = data
        except Exception as e:
            logger.warning(f"Could not load decision memory: {e}")
    
    def _save(self):
        """Save decisions to storage"""
        try:
            import os
            os.makedirs(os.path.dirname(self.storage_path), exist_ok=True)
            with open(self.storage_path, 'w') as f:
                json.dump(self.decisions, f, indent=2)
        except Exception as e:
            logger.error(f"Could not save decision memory: {e}")
    
    def record(self, decision: DecisionRecord):
        """Record a new decision"""
        self.decisions[decision.decision_id] = decision.to_dict()
        self._save()
    
    def get(self, decision_id: str) -> Optional[Dict]:
        """Get a decision by ID"""
        return self.decisions.get(decision_id)
    
    def update(self, decision: DecisionRecord):
        """Update an existing decision"""
        self.decisions[decision.decision_id] = decision.to_dict()
        self._save()
    
    def get_recent(self, limit: int = 10) -> List[Dict]:
        """Get recent decisions"""
        sorted_decisions = sorted(
            self.decisions.values(),
            key=lambda x: x['timestamp'],
            reverse=True
        )
        return sorted_decisions[:limit]
    
    def get_success_rate(self) -> float:
        """Calculate overall success rate"""
        completed = [d for d in self.decisions.values() if d.get('success') is not None]
        if not completed:
            return 0.5  # Default
        
        successful = sum(1 for d in completed if d['success'])
        return successful / len(completed)


class LLMDecisionRouter:
    """
    Routes decision-making through LLM reasoning models.
    
    Core innovation: No hardcoded actions!
    - LLM generates options dynamically
    - SyMod validates mathematically
    - Memory learns from outcomes
    """
    
    def __init__(self, agi_kernel):
        self.agi = agi_kernel
        
        # Decision silos (context providers)
        self.goal_stack = getattr(agi_kernel, 'goal_stack', None)
        self.opportunity_detector = getattr(agi_kernel, 'opportunity_detector', None)
        self.predictive_suggestions = getattr(agi_kernel, 'predictive_suggestions', None)
        self.content_strategy = getattr(agi_kernel, 'content_strategy', None)
        self.world_state = getattr(agi_kernel, 'world_state', None)
        
        # Reasoning models
        self.grok_ai = None
        self.deepseek_ai = None
        self._init_reasoning_models()
        
        # Mathematical validator (SyMod)
        self.symod = getattr(agi_kernel, 'symod', None)
        
        # Learning system
        self.episodic_memory = getattr(agi_kernel, 'episodic_memory', None)
        self.decision_memory = DecisionMemory()
        
        logger.info("🧠 LLM Decision Router initialized")
        logger.info(f"   Reasoning Models: Grok={self.grok_ai is not None}, DeepSeek={self.deepseek_ai is not None}")
        logger.info(f"   SyMod Validation: {self.symod is not None}")
    
    def _init_reasoning_models(self):
        """Initialize LLM reasoning models"""
        try:
            # Try to import Grok
            from grok_ai import GrokAI
            self.grok_ai = GrokAI()
            logger.info("✅ Grok reasoning model loaded")
        except ImportError:
            logger.warning("⚠️ Grok not available")
        
        try:
            # Try to import DeepSeek
            from deepseek_ai import DeepSeekAI
            self.deepseek_ai = DeepSeekAI()
            logger.info("✅ DeepSeek reasoning model loaded")
        except ImportError:
            logger.warning("⚠️ DeepSeek not available")
    
    async def decide_next_action(self) -> Optional[Dict]:
        """
        Main decision loop using LLM + SyMod + Memory.
        
        Returns:
            Best action to take, or None
        """
        
        logger.info("🎯 Starting LLM decision process...")
        
        # Step 1: Gather context from all silos
        context = await self._gather_decision_context()
        
        if not context.get('goals') and not context.get('opportunities'):
            logger.info("   No goals or opportunities - skipping decision")
            return None
        
        # Step 2: Generate options via LLM reasoning
        options = await self._generate_options_via_llm(context)
        
        if not options:
            logger.warning("   No options generated by LLM")
            return None
        
        logger.info(f"   Generated {len(options)} options")
        
        # Step 3: Score each option with SyMod
        scored_options = await self._score_options_with_symod(options, context)
        
        # Step 4: Select best option
        best_option = self._select_best_option(scored_options)
        
        if not best_option:
            logger.warning("   No valid option selected")
            return None
        
        # Step 5: Record decision to memory
        decision_record = self._record_decision(
            context=context,
            options=[o.to_dict() for o in scored_options],
            selected=best_option.to_dict(),
            reasoning=best_option.symod_reasoning
        )
        
        logger.info(f"✅ Decision made: {best_option.action[:60]}...")
        logger.info(f"   SyMod Score: {best_option.symod_score:.2f}/100")
        logger.info(f"   Decision ID: {decision_record.decision_id}")
        
        # Step 6: Convert to action format for execution
        action = self._option_to_action(best_option, decision_record.decision_id)
        
        return action
    
    async def _gather_decision_context(self) -> Dict:
        """
        Gather context from all decision silos.
        
        Returns rich context for LLM reasoning.
        """
        
        context = {
            'timestamp': datetime.now().isoformat(),
            'hour': datetime.now().hour,
            'day_of_week': datetime.now().strftime('%A'),
            'goals': [],
            'opportunities': [],
            'suggestions': [],
            'world_state': {},
            'performance': {},
            'content_state': {}
        }
        
        # Goals from Goal Stack
        if self.goal_stack:
            try:
                active_goals = self.goal_stack.get_active_goals(limit=5)
                context['goals'] = [
                    {
                        'id': g.id,
                        'description': g.description,
                        'priority': g.priority,
                        'attempts': g.attempts,
                        'context': g.context
                    }
                    for g in active_goals
                ]
            except Exception as e:
                logger.warning(f"Could not get goals: {e}")
        
        # Opportunities from Opportunity Detector
        if self.opportunity_detector:
            try:
                opps = self.opportunity_detector.detect_opportunities()
                context['opportunities'] = [
                    {
                        'type': o.opportunity_type,
                        'title': o.title,
                        'description': o.description,
                        'confidence': o.confidence,
                        'impact': o.potential_impact
                    }
                    for o in opps[:5]
                ]
            except Exception as e:
                logger.warning(f"Could not get opportunities: {e}")
        
        # Suggestions from Predictive Suggestions
        if self.predictive_suggestions:
            try:
                suggestions = self.predictive_suggestions.generate_proactive_suggestions(limit=3)
                context['suggestions'] = [
                    {
                        'type': s.suggestion_type,
                        'message': s.message,
                        'priority': s.priority,
                        'confidence': s.confidence
                    }
                    for s in suggestions
                ]
            except Exception as e:
                logger.warning(f"Could not get suggestions: {e}")
        
        # World State snapshot
        if self.world_state:
            try:
                context['world_state'] = {
                    'trending_topics': self.world_state.get_trending_topics(limit=3),
                    'recent_events': len(self.world_state.get_events(limit=20)),
                    'active_platforms': self.world_state.get_active_platforms() if hasattr(self.world_state, 'get_active_platforms') else []
                }
            except Exception as e:
                logger.warning(f"Could not get world state: {e}")
        
        # Recent performance
        if self.episodic_memory:
            try:
                recent = self.episodic_memory.get_recent_episodes(limit=10)
                if recent:
                    # EpisodicMemory uses emotional_valence (-1 to 1), not success boolean
                    # Positive valence = success, negative = failure
                    positive_outcomes = sum(1 for e in recent if e.emotional_valence > 0)
                    success_rate = positive_outcomes / len(recent) if recent else 0.5
                    context['performance'] = {
                        'recent_success_rate': success_rate,
                        'total_actions': len(recent)
                    }
            except Exception as e:
                logger.warning(f"Could not get performance: {e}")
        
        # Content strategy state
        if self.content_strategy:
            try:
                context['content_state'] = {
                    'has_queued_topics': hasattr(self.content_strategy, 'get_queued_topics')
                }
            except Exception as e:
                logger.warning(f"Could not get content state: {e}")
        
        return context
    
    async def _generate_options_via_llm(self, context: Dict) -> List[DecisionOption]:
        """
        Use LLM reasoning to generate multiple action options.
        
        This is the KEY innovation - no hardcoded actions!
        """
        
        # Build prompt for LLM
        prompt = self._build_decision_prompt(context)
        
        # Try Grok first (better for strategic planning)
        if self.grok_ai:
            try:
                response = await self._call_grok_reasoning(prompt)
                options = self._parse_llm_response(response)
                if options:
                    logger.info(f"   Grok generated {len(options)} options")
                    return options
            except Exception as e:
                logger.warning(f"Grok reasoning failed: {e}")
        
        # Fallback to DeepSeek
        if self.deepseek_ai:
            try:
                response = await self._call_deepseek_reasoning(prompt)
                options = self._parse_llm_response(response)
                if options:
                    logger.info(f"   DeepSeek generated {len(options)} options")
                    return options
            except Exception as e:
                logger.warning(f"DeepSeek reasoning failed: {e}")
        
        logger.warning("No reasoning model available")
        return []
    
    def _build_decision_prompt(self, context: Dict) -> str:
        """Build prompt for LLM reasoning"""
        
        prompt = f"""You are AlleyBot's autonomous decision-making system. Analyze the current context and generate 3-5 high-quality action options.

CURRENT CONTEXT:

Time: {context['day_of_week']} {context['hour']}:00

Active Goals ({len(context['goals'])}):
"""
        
        for i, goal in enumerate(context['goals'][:3], 1):
            prompt += f"{i}. {goal['description']} (Priority: {goal['priority']}/10, Attempts: {goal['attempts']})\n"
        
        if context['opportunities']:
            prompt += f"\nDetected Opportunities ({len(context['opportunities'])}):\n"
            for i, opp in enumerate(context['opportunities'][:3], 1):
                prompt += f"{i}. {opp['title']} - {opp['description']} (Confidence: {opp['confidence']:.0%})\n"
        
        if context['suggestions']:
            prompt += f"\nProactive Suggestions ({len(context['suggestions'])}):\n"
            for i, sug in enumerate(context['suggestions'], 1):
                prompt += f"{i}. {sug['message']} (Priority: {sug['priority']}/10)\n"
        
        if context['world_state'].get('trending_topics'):
            prompt += "\nTrending Topics:\n"
            for topic in context['world_state']['trending_topics']:
                prompt += f"- {topic.get('topic', 'Unknown')} ({topic.get('count', 0)} mentions)\n"
        
        if context['performance']:
            prompt += "\nRecent Performance:\n"
            prompt += f"- Success Rate: {context['performance']['recent_success_rate']:.0%}\n"
            prompt += f"- Total Actions: {context['performance']['total_actions']}\n"
        
        prompt += """
TASK:
Generate 3-5 diverse, specific action options that AlleyBot could take RIGHT NOW. Each option should:
1. Help achieve active goals OR capitalize on opportunities
2. Be specific and immediately actionable
3. Include clear expected outcome
4. Consider current time and context
5. Be realistic given available resources

Format EXACTLY as follows for each option:

OPTION 1:
ACTION: [Specific action to take - be very clear and actionable]
GOAL: [Which goal this helps achieve, or "Opportunity" if capitalizing on opportunity]
OUTCOME: [What specific result you expect from this action]
TIMING: [When to execute - "now", "in 1 hour", "at 9am tomorrow", etc.]
RESOURCES: [What's needed - API calls, content, data, etc.]
RISK: [low/medium/high and why]

Generate options now (minimum 3, maximum 5):"""
        
        return prompt
    
    async def _call_grok_reasoning(self, prompt: str) -> str:
        """Call Grok reasoning model"""
        if not self.grok_ai:
            raise Exception("Grok not available")
        
        # Use Grok's reasoning capabilities
        response = await self.grok_ai.reason(
            prompt=prompt,
            temperature=0.7,
            max_tokens=1500
        )
        
        return response
    
    async def _call_deepseek_reasoning(self, prompt: str) -> str:
        """Call DeepSeek reasoning model"""
        if not self.deepseek_ai:
            raise Exception("DeepSeek not available")
        
        # Use DeepSeek Reasoner
        response = await self.deepseek_ai.reason(
            prompt=prompt,
            model='deepseek-reasoner',
            temperature=0.7,
            max_tokens=1500
        )
        
        return response
    
    def _parse_llm_response(self, response: str) -> List[DecisionOption]:
        """Parse LLM response into structured options"""
        
        options = []
        lines = response.split('\n')
        
        current_option = {}
        
        for line in lines:
            line = line.strip()
            
            if line.startswith('OPTION'):
                if current_option and 'action' in current_option:
                    try:
                        option = DecisionOption(
                            action=current_option.get('action', ''),
                            goal_alignment=current_option.get('goal', ''),
                            expected_outcome=current_option.get('outcome', ''),
                            timing=current_option.get('timing', 'now'),
                            resources_needed=current_option.get('resources', ''),
                            risk_level=current_option.get('risk', 'medium')
                        )
                        options.append(option)
                    except Exception as e:
                        logger.warning(f"Could not parse option: {e}")
                current_option = {}
            
            elif line.startswith('ACTION:'):
                current_option['action'] = line.replace('ACTION:', '').strip()
            elif line.startswith('GOAL:'):
                current_option['goal'] = line.replace('GOAL:', '').strip()
            elif line.startswith('OUTCOME:'):
                current_option['outcome'] = line.replace('OUTCOME:', '').strip()
            elif line.startswith('TIMING:'):
                current_option['timing'] = line.replace('TIMING:', '').strip()
            elif line.startswith('RESOURCES:'):
                current_option['resources'] = line.replace('RESOURCES:', '').strip()
            elif line.startswith('RISK:'):
                current_option['risk'] = line.replace('RISK:', '').strip()
        
        # Don't forget last option
        if current_option and 'action' in current_option:
            try:
                option = DecisionOption(
                    action=current_option.get('action', ''),
                    goal_alignment=current_option.get('goal', ''),
                    expected_outcome=current_option.get('outcome', ''),
                    timing=current_option.get('timing', 'now'),
                    resources_needed=current_option.get('resources', ''),
                    risk_level=current_option.get('risk', 'medium')
                )
                options.append(option)
            except Exception as e:
                logger.warning(f"Could not parse final option: {e}")
        
        return options
    
    async def _score_options_with_symod(self, options: List[DecisionOption], 
                                       context: Dict) -> List[DecisionOption]:
        """
        Use SyMod to mathematically score each option.
        
        If SyMod not available, use heuristic scoring.
        """
        
        for option in options:
            if self.symod:
                # Use SyMod for mathematical scoring
                try:
                    score = await self._symod_score_option(option, context)
                    option.symod_score = score['total_score']
                    option.symod_breakdown = score.get('breakdown', {})
                    option.symod_reasoning = score.get('reasoning', '')
                    option.symod_confidence = score.get('confidence', 0.5)
                except Exception as e:
                    logger.warning(f"SyMod scoring failed: {e}")
                    option.symod_score = self._heuristic_score(option, context)
            else:
                # Fallback to heuristic scoring
                option.symod_score = self._heuristic_score(option, context)
        
        return options
    
    async def _symod_score_option(self, option: DecisionOption, context: Dict) -> Dict:
        """Score option using SyMod mathematical validation"""
        
        # Build SyMod evaluation context
        symod_context = {
            'action': option.action,
            'goal_alignment': option.goal_alignment,
            'expected_outcome': option.expected_outcome,
            'risk_level': option.risk_level,
            'goals': context['goals'],
            'performance': context['performance']
        }
        
        # Ask SyMod to evaluate
        # Note: This assumes SyMod has an evaluate_decision method
        # Adjust based on actual SyMod API
        if hasattr(self.symod, 'evaluate_decision'):
            result = await self.symod.evaluate_decision(symod_context)
        else:
            # Fallback if method doesn't exist
            result = {
                'total_score': self._heuristic_score(option, context),
                'breakdown': {},
                'reasoning': 'SyMod evaluation not available',
                'confidence': 0.5
            }
        
        return result
    
    def _heuristic_score(self, option: DecisionOption, context: Dict) -> float:
        """
        Heuristic scoring when SyMod not available.
        
        Scores 0-100 based on:
        - Goal alignment
        - Risk level
        - Timing appropriateness
        - Resource efficiency
        """
        
        score = 50.0  # Base score
        
        # Goal alignment bonus
        if option.goal_alignment and option.goal_alignment != 'Opportunity':
            score += 20
        
        # Risk penalty
        if 'low' in option.risk_level.lower():
            score += 15
        elif 'high' in option.risk_level.lower():
            score -= 15
        
        # Timing bonus (prefer "now" during active hours)
        hour = context.get('hour', 12)
        if 'now' in option.timing.lower() and 9 <= hour <= 17:
            score += 10
        
        # Success rate bonus
        if context.get('performance', {}).get('recent_success_rate', 0) > 0.7:
            score += 5  # On a roll, be confident
        
        return max(0, min(100, score))
    
    def _select_best_option(self, scored_options: List[DecisionOption]) -> Optional[DecisionOption]:
        """Select best option based on SyMod scores"""
        
        if not scored_options:
            return None
        
        # Sort by score
        scored_options.sort(key=lambda x: x.symod_score, reverse=True)
        
        best = scored_options[0]
        
        # Log all options for transparency
        logger.info("   Option scores:")
        for i, opt in enumerate(scored_options, 1):
            logger.info(f"   {i}. {opt.action[:50]}... → {opt.symod_score:.2f}/100")
        
        return best
    
    def _record_decision(self, context: Dict, options: List[Dict],
                        selected: Dict, reasoning: str) -> DecisionRecord:
        """Record decision to memory"""
        
        decision_id = f"decision_{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        
        record = DecisionRecord(
            decision_id=decision_id,
            timestamp=datetime.now().isoformat(),
            context=context,
            options_considered=options,
            selected_option=selected,
            symod_reasoning=reasoning
        )
        
        self.decision_memory.record(record)
        
        return record
    
    def _option_to_action(self, option: DecisionOption, decision_id: str) -> Dict:
        """Convert DecisionOption to action format for execution"""
        
        return {
            'action_type': 'llm_decision',
            'description': option.action,
            'goal_alignment': option.goal_alignment,
            'expected_outcome': option.expected_outcome,
            'timing': option.timing,
            'resources': option.resources_needed,
            'risk': option.risk_level,
            'symod_score': option.symod_score,
            'decision_id': decision_id,
            'source': 'llm_decision_router'
        }
    
    async def record_outcome(self, decision_id: str, outcome: Dict, success: bool):
        """
        Record outcome of a decision for learning.
        
        Completes the learning loop.
        """
        
        decision_dict = self.decision_memory.get(decision_id)
        
        if decision_dict:
            # Extract learning
            learning = self._extract_learning(decision_dict, outcome, success)
            
            # Update decision record
            decision_dict['outcome'] = outcome
            decision_dict['success'] = success
            decision_dict['learning'] = learning
            
            # Convert back to DecisionRecord for update
            record = DecisionRecord(
                decision_id=decision_dict['decision_id'],
                timestamp=decision_dict['timestamp'],
                context=decision_dict['context'],
                options_considered=decision_dict['options_considered'],
                selected_option=decision_dict['selected_option'],
                symod_reasoning=decision_dict['symod_reasoning'],
                outcome=outcome,
                success=success,
                learning=learning
            )
            
            self.decision_memory.update(record)
            
            # Also store to episodic memory
            if self.episodic_memory:
                try:
                    self.episodic_memory.record_episode(
                        action_type=decision_dict['selected_option']['action'],
                        context=decision_dict['context'],
                        outcome=outcome,
                        success=success
                    )
                except Exception as e:
                    logger.warning(f"Could not record to episodic memory: {e}")
            
            logger.info(f"📚 Decision outcome recorded: {decision_id}")
            logger.info(f"   Success: {success}")
            logger.info(f"   Learning: {learning}")
    
    def _extract_learning(self, decision: Dict, outcome: Dict, success: bool) -> str:
        """Extract learning from decision outcome"""
        
        selected = decision['selected_option']
        
        if success:
            return f"Action '{selected['action'][:50]}...' succeeded. Expected: {selected['expected_outcome']}. Actual: {outcome.get('result', 'Unknown')}. Reinforce this pattern."
        else:
            return f"Action '{selected['action'][:50]}...' failed. Expected: {selected['expected_outcome']}. Actual: {outcome.get('error', 'Unknown')}. Avoid this pattern."


def create_llm_decision_router(agi_kernel):
    """Factory function to create LLM Decision Router"""
    return LLMDecisionRouter(agi_kernel)
